#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: july-devops
  labels:
    app: ranty
spec:
 replicas: 2
 selector:
   matchLabels:
     app: ranty
 template:
   metadata:
     labels:
       app: ranty
   spec:
     containers:
     - name: iterncon
       image: adegokeobafemi/july-devops:latest
       ports:
       - containerPort: 8080
