#Service Type nodePort
apiVersion: v1
kind: Service
metadata:
  name: ranty-service
  labels:
    app: service
spec:
  selector:
    app: ranty
  type: NodePort
  ports:
  - nodePort: 30022
    port: 8080
    targetPort: 8080
