#Service Type nodePort
apiVersion: v1
kind: Service
metadata:
  name: ranty
  labels:
    app: ranty
spec:
  selector:
    app: ranty
  type: NodePort
  ports:
  - nodePort: 30015
    port: 8080
    targetPort: 8080
